---
apiVersion: v1
kind: Secret
metadata:
  name: bolt-secrets
data:
  bolt-api-service.json: {{ .Values.global.google_service_account | b64enc }}
  secrets.py: {{ .Values.secrets | b64enc }}
type: Opaque
