{{- if ( and (.Values.global.google_service_account) (.Values.secrets)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: bolt-secrets
data:
  bolt-api-service.json: {{ .Values.global.google_service_account | b64enc }}
  secrets.py: {{ list .Values.secrets (include "endpoints" .) | join "" | b64enc }}
type: Opaque
{{- end -}}