kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "bolt-api.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "bolt-api.fullname" . }}
  namespace: {{ required "missing" .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "bolt-api.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
