kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bolt-api
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["get", "list", "create", "delete", "watch"]
