---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-files
data:
  id_rsa: {{ .Values.id_rsa | b64enc }}
  id_rsa.pub: {{ .Values.id_rsa_pub | b64enc }}
  known_hosts: {{ .Values.known_hosts | b64enc }}
type: Opaque