apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workflow-creator.fullname" . }}
  labels:
{{ include "workflow-creator.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.creator.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "workflow-creator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "workflow-creator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccount: bolt-workflow-creator
    {{- with .Values.creator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.creator.image.repository }}:{{ .Values.creator.image.tag }}"
          imagePullPolicy: {{ .Values.creator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health-check
              port: http
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
          resources:
            {{- toYaml .Values.creator.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.creator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.creator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
